import type { ProductSeries } from '@/types/product';

export const PRODUCT_SERIES: ProductSeries[] = [
  // Split group
  {
    id: 'split-cs',
    groupId: 'split',
    name: 'CS',
    fullName: 'Commercial Split System Series',
    modelPrefix: 'CS',
    minTons: 1.5,
    maxTons: 20,
    tonRangeLabel: '1.5 – 20 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Commercial split systems with multi-position indoor air handlers for ceiling, floor, or closet installation.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'split-ds',
    groupId: 'split',
    name: 'DS',
    fullName: 'Ducted Split System Series',
    modelPrefix: 'DS',
    minTons: 2,
    maxTons: 15,
    tonRangeLabel: '2 – 15 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Inverter ducted split systems offering variable capacity operation from 20–110% to precisely match the cooling load.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // Mini-split group
  {
    id: 'ms-wall',
    groupId: 'mini-split',
    name: 'MS-W',
    fullName: 'Mini-Split Wall-Mounted Series',
    modelPrefix: 'MS-W',
    minTons: 0.75,
    maxTons: 4,
    tonRangeLabel: '0.75 – 4 Tons',
    refrigerants: ['R-32'],
    primaryRefrigerant: 'R-32',
    keyDifferentiator: '',
    description: 'Residential and light commercial wall-mounted mini-split units with inverter technology for maximum efficiency.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'ms-cas',
    groupId: 'mini-split',
    name: 'MS-CAS',
    fullName: 'Cassette / Ceiling Mini-Split Series',
    modelPrefix: 'MS-C',
    minTons: 1,
    maxTons: 10,
    tonRangeLabel: '1 – 10 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Ceiling-recessed cassette units for commercial spaces. Flush-fit grille for aesthetically clean installations.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // NGW Fan Coil Units (real data from NGW Selection Software)
  {
    id: 'ngw',
    groupId: 'fan-coil',
    name: 'NGW',
    fullName: 'NGW Chilled Water Fan Coil Unit Series',
    modelPrefix: 'NGW',
    minTons: 6,
    maxTons: 24,
    tonRangeLabel: '6 – 24 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '3-row & 4-row coil options',
    description: 'Belt-driven centrifugal ducted fan coil units for chilled water systems. Available in 3-row and 4-row coil configurations. Power supply 415V/3Ph/50Hz.',
    features: ['Belt-driven DIDW centrifugal fan', 'Copper tube / aluminum fin coil', '3/8" or 1/2" copper tubes', 'Galvanized steel casing with fibreglass insulation', 'Optional high-static drive kit'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // Air-Cooled Chillers (legacy scroll, kept for backward compatibility)
  {
    id: 'ngw-scroll',
    groupId: 'chiller-air',
    name: 'NGW-S',
    fullName: 'Air-Cooled Scroll Chiller Series',
    modelPrefix: 'NGW-S',
    minTons: 20,
    maxTons: 80,
    tonRangeLabel: '20 – 80 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Air-cooled scroll chillers for small to medium central plants. Integrated pump, expansion tank, and controls module available.',
    features: [],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'acsc',
    groupId: 'chiller-air',
    name: 'ACSC',
    fullName: 'Air-Cooled Screw Chiller Series',
    modelPrefix: 'ACSC',
    minTons: 81,
    maxTons: 500,
    tonRangeLabel: '81 – 500 Tons',
    refrigerants: ['R-134a'],
    primaryRefrigerant: 'R-134a',
    keyDifferentiator: 'Hanbell screw compressors, high-ambient Gulf operation',
    description: 'Air-cooled screw chillers (ACSC080–ACSC500) engineered for high-ambient Gulf climate operation. Hanbell screw compressors, R-134a refrigerant, shell & tube evaporator, electronic expansion valve, and microprocessor controls. 34 models from 81 to 500 TR.',
    features: ['Hanbell screw compressors (RC2 series)', 'Electronic expansion valve', 'Shell & tube evaporator', 'Microprocessor controller', 'Optional: copper fins, flange connection, BMS', '415V / 3Ph / 50Hz'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // Water-cooled chillers
  {
    id: 'wcc-scroll',
    groupId: 'chiller-water',
    name: 'WCC-S',
    fullName: 'Water-Cooled Scroll Chiller',
    modelPrefix: 'WCC-S',
    minTons: 50,
    maxTons: 200,
    tonRangeLabel: '50 – 200 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Water-cooled scroll chillers delivering COP up to 6.5 for applications with cooling tower or process water.',
    features: [],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'wcc-screw',
    groupId: 'chiller-water',
    name: 'WCC-SC',
    fullName: 'Water-Cooled Screw Chiller',
    modelPrefix: 'WCC-SC',
    minTons: 150,
    maxTons: 500,
    tonRangeLabel: '150 – 500 Tons',
    refrigerants: ['R-134a'],
    primaryRefrigerant: 'R-134a',
    keyDifferentiator: '',
    description: 'Large water-cooled screw chillers for major district cooling and central plant applications.',
    features: [],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // CCU group
  {
    id: 'ccu-std',
    groupId: 'ccu',
    name: 'CCU',
    fullName: 'Standard Condensing Unit Series',
    modelPrefix: 'CCU',
    minTons: 1,
    maxTons: 15,
    tonRangeLabel: '1 – 15 Tons',
    refrigerants: ['R-404A', 'R-410A'],
    primaryRefrigerant: 'R-404A',
    keyDifferentiator: '',
    description: 'Medium-temperature remote condensing units designed for commercial refrigeration display cases and walk-in coolers.',
    features: [],
    isChiller: false,
    isCCU: true,
    hasDualRefrigerant: true,
  },
  {
    id: 'ccu-lt',
    groupId: 'ccu',
    name: 'CCU-LT',
    fullName: 'Low-Temperature Condensing Unit Series',
    modelPrefix: 'CCU-LT',
    minTons: 1,
    maxTons: 25,
    tonRangeLabel: '1 – 25 Tons',
    refrigerants: ['R-404A'],
    primaryRefrigerant: 'R-404A',
    keyDifferentiator: '',
    description: 'Low-temperature condensing units for blast freezers, ice cream storage, and frozen food distribution centers.',
    features: [],
    isChiller: false,
    isCCU: true,
    hasDualRefrigerant: false,
  },
  // Precision cooling
  {
    id: 'prec-dc',
    groupId: 'precision',
    name: 'PDU',
    fullName: 'Precision Data Center Cooling Unit',
    modelPrefix: 'PDU',
    minTons: 5,
    maxTons: 30,
    tonRangeLabel: '5 – 30 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Precision cooling units for data centers, server rooms, and telecom equipment. Tight temperature and humidity control.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'prec-tele',
    groupId: 'precision',
    name: 'PTU',
    fullName: 'Precision Telecom Cooling Unit',
    modelPrefix: 'PTU',
    minTons: 1,
    maxTons: 10,
    tonRangeLabel: '1 – 10 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Weatherproof precision cooling units for outdoor telecom shelters, base stations, and remote equipment cabinets.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // Fan coil
  {
    id: 'fcu',
    groupId: 'fan-coil',
    name: 'FCU',
    fullName: 'Fan Coil Unit Series',
    modelPrefix: 'FCU',
    minTons: 0.5,
    maxTons: 5,
    tonRangeLabel: '0.5 – 5 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Chilled water fan coil units in concealed horizontal, vertical console, and ceiling cassette configurations.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // PNGF / PNGC / CIPK / SPU — Rooftop Packaged
  // NGCC / CHCC / NGCF / CHCF — Split (concealed ducted)
  {
    id: 'pngf',
    groupId: 'pac',
    name: 'PNGF',
    fullName: 'PNGF Rooftop Packaged Series',
    modelPrefix: 'PNGF',
    minTons: 4,
    maxTons: 29,
    tonRangeLabel: '4 – 29 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'PNGF rooftop packaged units with R-410A refrigerant for commercial and industrial cooling. Scroll compressors, 415V/3Ph/50Hz.',
    features: ['Scroll compressors', 'R-410A refrigerant', '415V/3Ph/50Hz', 'Weatherproof rooftop construction'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'pngc',
    groupId: 'pac',
    name: 'PNGC',
    fullName: 'PNGC Rooftop Package Series',
    modelPrefix: 'PNGC',
    minTons: 4,
    maxTons: 33.5,
    tonRangeLabel: '4 – 33.5 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'R-407C, high-ambient Gulf operation',
    description: 'Rooftop packaged units (PNGC-048 to PNGC-400) engineered for high-ambient Gulf climate. Scroll compressors, R-407C refrigerant, 415V/3Ph/50Hz. 16 models from 4 to 33.5 TR.',
    features: ['Scroll compressors', 'R-407C refrigerant', '415V/3Ph/50Hz', 'Weatherproof rooftop construction', 'EER up to 12.8 at 95°F ambient'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'ngcc',
    groupId: 'split',
    name: 'NGCC',
    fullName: 'NGCC/NGEC New Generation Compact Ducted Split Series',
    modelPrefix: 'NGCC',
    minTons: 6.3,
    maxTons: 28,
    tonRangeLabel: '6.3 – 28 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'Concealed ducted split, hermetic compressor tropical',
    description: 'New Generation Compact concealed ducted split units (NGCC/NGEC-076 to -340) designed for tropical climates. Hermetic scroll compressors, R-407C, separate outdoor and indoor units. 12 models from 6.3 to 28 TR.',
    features: ['Hermetic scroll compressors', 'R-407C refrigerant', 'Separate outdoor/indoor units', 'Concealed ducted indoor unit', 'Tropical design'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'chcc',
    groupId: 'split',
    name: 'CHCC / CHEC',
    fullName: 'CHCC / CHEC Concealed Ducted Split Series',
    modelPrefix: 'CHCC',
    minTons: 2,
    maxTons: 5.5,
    tonRangeLabel: '2 – 5.5 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'Concealed ducted, EER up to 14.2',
    description: 'Compact concealed ducted split units (CHCC/CHEC-024 to -060) for residential and light commercial applications. R-407C refrigerant, high EER ratings up to 14.2. 6 models from 2 to 5.5 TR.',
    features: ['Scroll compressors', 'R-407C refrigerant', 'Concealed ducted indoor unit', 'EER up to 14.2 at 95°F', 'Compact outdoor unit'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'cipk',
    groupId: 'pac',
    name: 'CIPK',
    fullName: 'CIPK Series',
    modelPrefix: 'CIPK',
    minTons: 4,
    maxTons: 10,
    tonRangeLabel: '4 – 10 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'CIPK series compact packaged units for precision cooling applications.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'spu',
    groupId: 'pac',
    name: 'SPU',
    fullName: 'SPU Series',
    modelPrefix: 'SPU',
    minTons: 35,
    maxTons: 100,
    tonRangeLabel: '35 – 100 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'SPU series split packaged units for large-capacity commercial cooling applications.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // CHCF / NGCF — Split
  {
    id: 'chcf',
    groupId: 'split',
    name: 'CHCF',
    fullName: 'CHCF Concealed Ducted Split Series',
    modelPrefix: 'CHCF',
    minTons: 2,
    maxTons: 5.5,
    tonRangeLabel: '2 – 5.5 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'R-410A variant, concealed ducted',
    description: 'CHCF concealed ducted split units for residential and light commercial applications. R-410A refrigerant.',
    features: ['Scroll compressors', 'R-410A refrigerant', 'Concealed ducted indoor unit', 'Compact outdoor unit'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'ngcf',
    groupId: 'split',
    name: 'NGCF',
    fullName: 'NGCF/NGEF New Generation Concealed Ducted Split Series',
    modelPrefix: 'NGCF',
    minTons: 6.3,
    maxTons: 28,
    tonRangeLabel: '6.3 – 28 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'R-410A variant, tropical design',
    description: 'NGCF/NGEF new generation concealed ducted split units for tropical climates. R-410A refrigerant, separate outdoor and indoor units.',
    features: ['Hermetic scroll compressors', 'R-410A refrigerant', 'Separate outdoor/indoor units', 'Concealed ducted indoor unit', 'Tropical design'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
];
