import type { ProductSeries } from '@/types/product';

export const PRODUCT_SERIES: ProductSeries[] = [
  // PAC group
  {
    id: 'pac-r',
    groupId: 'pac',
    name: 'PAC-R',
    fullName: 'Packaged Air-Cooled Rooftop Series',
    modelPrefix: 'CPACR',
    minTons: 5,
    maxTons: 70,
    tonRangeLabel: '5 – 70 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Rooftop-optimized, low-profile design with factory-installed economizer option',
    description: 'The PAC-R series are rooftop packaged units designed for flat-roof commercial buildings. All units are factory-tested and shipped ready to install.',
    features: ['Low profile for rooftop clearance', 'Integrated economizer ready', 'Scroll compressors up to 4 circuits', 'Weatherproof powder-coated cabinet', 'BACnet/Modbus ready'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'pac-f',
    groupId: 'pac',
    name: 'PAC-F',
    fullName: 'Packaged Air-Cooled Floor-Mounted Series',
    modelPrefix: 'CPACF',
    minTons: 3,
    maxTons: 30,
    tonRangeLabel: '3 – 30 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Floor-mounted for plant rooms and equipment areas; vertical or horizontal discharge',
    description: 'Floor-mounted packaged units ideal for indoor plant rooms. Available in vertical upflow and horizontal discharge configurations.',
    features: ['Vertical or horizontal discharge', 'Compact footprint', 'Optional electric heater up to 72kW', 'Phase-failure protection standard', 'Factory swing testing'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'pac-g',
    groupId: 'pac',
    name: 'PAC-G',
    fullName: 'Packaged Air-Cooled Gas/Elec Series',
    modelPrefix: 'CPACG',
    minTons: 5,
    maxTons: 25,
    tonRangeLabel: '5 – 25 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Dual fuel: electric cooling + natural gas heating in one cabinet',
    description: 'Combination gas/electric rooftop units for regions requiring both cooling and gas heating in a single package.',
    features: ['Natural gas furnace integrated', 'Up to 200,000 BTU/h heating', 'Single point power', 'Modulating gas valve', 'High-static option available'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // Split group
  {
    id: 'split-cs',
    groupId: 'split',
    name: 'CS',
    fullName: 'Commercial Split System Series',
    modelPrefix: 'CCS',
    minTons: 1.5,
    maxTons: 20,
    tonRangeLabel: '1.5 – 20 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'High-efficiency commercial split with SEER2 up to 18, multi-position air handler',
    description: 'Commercial split systems with multi-position indoor air handlers for ceiling, floor, or closet installation.',
    features: ['Multi-position AHU', 'Up to 18 SEER2', 'Scroll compressors', 'Optional hot gas reheat', 'Communicating controls'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'split-ds',
    groupId: 'split',
    name: 'DS',
    fullName: 'Ducted Split System Series',
    modelPrefix: 'CDS',
    minTons: 2,
    maxTons: 15,
    tonRangeLabel: '2 – 15 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Inverter-driven variable capacity for precise comfort control and low part-load power',
    description: 'Inverter ducted split systems offering variable capacity operation from 20–110% to precisely match the cooling load.',
    features: ['Inverter compressor 20–110%', 'R-32 option for lower GWP', 'Ultra-quiet indoor unit', 'Built-in Wi-Fi controller', 'Auto-restart after power failure'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // Mini-split group
  {
    id: 'ms-wall',
    groupId: 'mini-split',
    name: 'MS-W',
    fullName: 'Mini-Split Wall-Mounted Series',
    modelPrefix: 'CMS-W',
    minTons: 0.75,
    maxTons: 4,
    tonRangeLabel: '0.75 – 4 Tons',
    refrigerants: ['R-32'],
    primaryRefrigerant: 'R-32',
    keyDifferentiator: 'Ultra-slim wall-mounted head with 4-way airflow and built-in Wi-Fi',
    description: 'Residential and light commercial wall-mounted mini-split units with inverter technology for maximum efficiency.',
    features: ['R-32 refrigerant (GWP 675)', 'Up to 28 SEER', 'Self-cleaning function', '4-way auto-swing', 'Sleep mode & weekly timer'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'ms-cas',
    groupId: 'mini-split',
    name: 'MS-CAS',
    fullName: 'Cassette / Ceiling Mini-Split Series',
    modelPrefix: 'CMS-C',
    minTons: 1,
    maxTons: 10,
    tonRangeLabel: '1 – 10 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Ceiling cassette with 360° airflow distribution, recessed installation',
    description: 'Ceiling-recessed cassette units for commercial spaces. Flush-fit grille for aesthetically clean installations.',
    features: ['360° or 2-way airflow', 'Auto-adjusting louvers', 'Built-in drain pump', 'Group control up to 16 units', 'R-32 variant available'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // Air-Cooled Chillers
  {
    id: 'ngw-scroll',
    groupId: 'chiller-air',
    name: 'NGW-S',
    fullName: 'Air-Cooled Scroll Chiller Series',
    modelPrefix: 'CNGWS',
    minTons: 20,
    maxTons: 80,
    tonRangeLabel: '20 – 80 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Modular scroll chiller, plug-and-play installation with integrated hydronic module',
    description: 'Air-cooled scroll chillers for small to medium central plants. Integrated pump, expansion tank, and controls module available.',
    features: ['Scroll compressors (2–8)', 'Integrated hydronic module option', 'Part load IPLV up to 14.5', 'BACnet/Modbus/LON', 'Hot gas bypass standard'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'acsc',
    groupId: 'chiller-air',
    name: 'ACSC',
    fullName: 'Air-Cooled Screw Chiller Series',
    modelPrefix: 'CACSC',
    minTons: 80,
    maxTons: 200,
    tonRangeLabel: '80 – 200 Tons',
    refrigerants: ['R-134a'],
    primaryRefrigerant: 'R-134a',
    keyDifferentiator: 'Twin-screw compressor for high IPLV at Gulf climate ambient temperatures up to 55°C',
    description: 'High-capacity air-cooled screw chillers engineered for high ambient operation in desert and Gulf climates.',
    features: ['Twin-screw compressors', 'IPLV up to 13.0 at 46°C ambient', 'Flooded evaporator', 'Variable speed condenser fans', 'Full load 55°C ambient rated'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // Water-cooled chillers
  {
    id: 'wcc-scroll',
    groupId: 'chiller-water',
    name: 'WCC-S',
    fullName: 'Water-Cooled Scroll Chiller',
    modelPrefix: 'CWCCS',
    minTons: 50,
    maxTons: 200,
    tonRangeLabel: '50 – 200 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'High-COP water-cooled scroll chiller for hotel and hospital central plants',
    description: 'Water-cooled scroll chillers delivering COP up to 6.5 for applications with cooling tower or process water.',
    features: ['COP up to 6.5', 'Shell and tube evaporator/condenser', '2–6 scroll compressor circuits', 'Touch-screen controller', 'Soft-start on all compressors'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'wcc-screw',
    groupId: 'chiller-water',
    name: 'WCC-SC',
    fullName: 'Water-Cooled Screw Chiller',
    modelPrefix: 'CWCCSC',
    minTons: 150,
    maxTons: 500,
    tonRangeLabel: '150 – 500 Tons',
    refrigerants: ['R-134a'],
    primaryRefrigerant: 'R-134a',
    keyDifferentiator: 'Centrifugal-class efficiency with screw reliability; IPLV up to 9.0',
    description: 'Large water-cooled screw chillers for major district cooling and central plant applications.',
    features: ['IPLV up to 9.0 kW/kW', 'Variable Vi (volume index) compressor', 'Pressure differential protection', 'Duplex oil system', 'Integrated thermal storage option'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // CCU group
  {
    id: 'ccu-std',
    groupId: 'ccu',
    name: 'CCU',
    fullName: 'Standard Condensing Unit Series',
    modelPrefix: 'CCCU',
    minTons: 1,
    maxTons: 15,
    tonRangeLabel: '1 – 15 Tons',
    refrigerants: ['R-404A', 'R-410A'],
    primaryRefrigerant: 'R-404A',
    keyDifferentiator: 'Medium-temperature condensing unit for supermarket display cases and cold rooms',
    description: 'Medium-temperature remote condensing units designed for commercial refrigeration display cases and walk-in coolers.',
    features: ['Medium/low temp operation', 'Scroll or reciprocating compressor', 'R-404A/R-407C compatible', 'Crankcase heater standard', 'Head pressure control'],
    isChiller: false,
    isCCU: true,
    hasDualRefrigerant: true,
  },
  {
    id: 'ccu-lt',
    groupId: 'ccu',
    name: 'CCU-LT',
    fullName: 'Low-Temperature Condensing Unit Series',
    modelPrefix: 'CCCULT',
    minTons: 1,
    maxTons: 25,
    tonRangeLabel: '1 – 25 Tons',
    refrigerants: ['R-404A'],
    primaryRefrigerant: 'R-404A',
    keyDifferentiator: 'Low-temperature rated to -35°C suction, purpose-built for blast freezers and frozen storage',
    description: 'Low-temperature condensing units for blast freezers, ice cream storage, and frozen food distribution centers.',
    features: ['Suction rated to -35°C', 'Tandem compressor option', 'Liquid injection cooling', 'Oil separator standard', 'Stainless steel drain pan'],
    isChiller: false,
    isCCU: true,
    hasDualRefrigerant: false,
  },
  // Precision cooling
  {
    id: 'prec-dc',
    groupId: 'precision',
    name: 'PDU',
    fullName: 'Precision Data Center Cooling Unit',
    modelPrefix: 'CPDU',
    minTons: 5,
    maxTons: 30,
    tonRangeLabel: '5 – 30 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'N+1 redundancy ready, ±0.5°C / ±3% RH precision, upflow or downflow',
    description: 'Precision cooling units for data centers, server rooms, and telecom equipment. Tight temperature and humidity control.',
    features: ['±0.5°C temperature accuracy', '±3% RH humidity control', 'Upflow or downflow', 'EC fan with variable speed', 'Remote monitoring via SNMP/BACnet'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'prec-tele',
    groupId: 'precision',
    name: 'PTU',
    fullName: 'Precision Telecom Cooling Unit',
    modelPrefix: 'CPTU',
    minTons: 1,
    maxTons: 10,
    tonRangeLabel: '1 – 10 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Outdoor-rated precision cooling for telecom shelters and outdoor equipment enclosures',
    description: 'Weatherproof precision cooling units for outdoor telecom shelters, base stations, and remote equipment cabinets.',
    features: ['IP54 weatherproof rating', 'Solar radiation shield option', 'Sand filter option', 'Battery backup compatible', '-20°C to +55°C ambient rated'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // Fan coil
  {
    id: 'fcu',
    groupId: 'fan-coil',
    name: 'FCU',
    fullName: 'Fan Coil Unit Series',
    modelPrefix: 'CFCU',
    minTons: 0.5,
    maxTons: 5,
    tonRangeLabel: '0.5 – 5 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Two-pipe and four-pipe fan coil units for chilled water systems; concealed, cassette, or console',
    description: 'Chilled water fan coil units in concealed horizontal, vertical console, and ceiling cassette configurations.',
    features: ['2-pipe or 4-pipe', 'Concealed/cassette/console', 'EC motor option', 'Built-in drain pump option', 'DDC control ready'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
];
