import type { ProductSeries } from '@/types/product';

export const PRODUCT_SERIES: ProductSeries[] = [
  // Split group
  {
    id: 'split-cs',
    groupId: 'split',
    name: 'DSSC / CDEC',
    fullName: 'Ducted Split System Series',
    modelPrefix: 'DSSC',
    minTons: 2,
    maxTons: 5,
    tonRangeLabel: '2 – 5 Tons',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: '',
    description: 'Commercial split systems with multi-position indoor air handlers for ceiling, floor, or closet installation.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'split-ds',
    groupId: 'split',
    name: 'DSSF / CDEF',
    fullName: 'Ducted Split System Series',
    modelPrefix: 'DSSF',
    minTons: 2,
    maxTons: 5,
    tonRangeLabel: '2 – 5 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Inverter ducted split systems offering variable capacity operation from 20–110% to precisely match the cooling load.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // Mini-split group
  {
    id: 'ms-wall',
    groupId: 'mini-split',
    name: 'MS-W',
    fullName: 'Mini-Split Wall-Mounted Series',
    modelPrefix: 'MS-W',
    minTons: 0.75,
    maxTons: 4,
    tonRangeLabel: '0.75 – 4 Tons',
    refrigerants: ['R-32'],
    primaryRefrigerant: 'R-32',
    keyDifferentiator: '',
    description: 'Residential and light commercial wall-mounted mini-split units with inverter technology for maximum efficiency.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'ms-cas',
    groupId: 'mini-split',
    name: 'MS-CAS',
    fullName: 'Cassette / Ceiling Mini-Split Series',
    modelPrefix: 'MS-C',
    minTons: 1,
    maxTons: 10,
    tonRangeLabel: '1 – 10 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Ceiling-recessed cassette units for commercial spaces. Flush-fit grille for aesthetically clean installations.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // NGW Fan Coil Units (real data from NGW Selection Software)
  {
    id: 'ngw',
    groupId: 'fan-coil',
    name: 'NGW',
    fullName: 'NGW Chilled Water Fan Coil Unit Series',
    modelPrefix: 'NGW',
    minTons: 6,
    maxTons: 24,
    tonRangeLabel: '6 – 24 Tons',
    cfmRangeLabel: '1,800 – 11,000 CFM',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '3-row & 4-row coil options',
    description: 'Belt-driven centrifugal ducted fan coil units for chilled water systems. Available in 3-row and 4-row coil configurations. Power supply 415V/3Ph/50Hz.',
    features: ['Belt-driven DIDW centrifugal fan', 'Copper tube / aluminum fin coil', '3/8" or 1/2" copper tubes', 'Galvanized steel casing with fibreglass insulation', 'Optional high-static drive kit'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    imageUrl: '/images/ngw.png',
  },
  // Chiller Group 1: ACSC – Air Cooled Screw Chiller, 80–500 TR, R-134a
  {
    id: 'acsc',
    groupId: 'chiller',
    name: 'ACSC',
    fullName: 'Air-Cooled Screw Chiller Series',
    modelPrefix: 'ACSC',
    minTons: 80,
    maxTons: 500,
    tonRangeLabel: '80 – 500 Tons',
    refrigerants: ['R-134a'],
    primaryRefrigerant: 'R-134a',
    keyDifferentiator: 'Hanbell screw compressors, high-ambient Gulf operation',
    description: 'Air-cooled screw chillers (ACSC080–ACSC500) engineered for high-ambient Gulf climate operation. Hanbell screw compressors, R-134a refrigerant, shell & tube evaporator, electronic expansion valve, and microprocessor controls.',
    features: ['Hanbell screw compressors (RC2 series)', 'Electronic expansion valve', 'Shell & tube evaporator', 'Microprocessor controller', 'Optional: copper fins, flange connection, BMS', '415V / 3Ph / 50Hz'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
    imageUrl: '/images/acsc.png',
  },
  // Chiller Group 2: THAC – Air Cooled, Brazed Plate HX, 3–50 TR, R-410A
  {
    id: 'thac',
    groupId: 'chiller',
    name: 'THAC',
    fullName: 'THAC Air-Cooled Chiller with Brazed Plate Heat Exchanger',
    modelPrefix: 'THAC',
    minTons: 3,
    maxTons: 50,
    tonRangeLabel: '3 – 50 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Brazed plate heat exchanger, compact design',
    description: 'Air-cooled chillers with brazed plate heat exchanger. Compact and efficient design for small to medium commercial applications. R-410A refrigerant.',
    features: ['Brazed plate heat exchanger', 'Scroll compressors', 'R-410A refrigerant', 'Compact footprint', '415V / 3Ph / 50Hz'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
    imageUrl: '/images/thac.png',
  },
  // Chiller Group 3: DHAC – Air Cooled, Shell & Tube HX, 20–100 TR, R-410A
  {
    id: 'dhac',
    groupId: 'chiller',
    name: 'DHAC',
    fullName: 'DHAC Air-Cooled Chiller with Shell & Tube Heat Exchanger',
    modelPrefix: 'DHAC',
    minTons: 20,
    maxTons: 100,
    tonRangeLabel: '20 – 100 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Shell & tube heat exchanger, robust design',
    description: 'Air-cooled chillers with shell & tube heat exchanger for medium-capacity applications. Robust construction for demanding environments. R-410A refrigerant.',
    features: ['Shell & tube heat exchanger', 'Scroll compressors', 'R-410A refrigerant', 'Heavy-duty construction', '415V / 3Ph / 50Hz'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
    imageUrl: '/images/dhac.png',
  },
  // Chiller Group 4: ACC (Brazed Plate) – Air Cooled, Brazed Plate HX, 3–17 TR, R-407C
  {
    id: 'acc-bp',
    groupId: 'chiller',
    name: 'ACC-BP',
    fullName: 'ACC Air-Cooled Chiller with Brazed Plate Heat Exchanger',
    modelPrefix: 'ACC',
    minTons: 3,
    maxTons: 17,
    tonRangeLabel: '3 – 17 Tons',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'Brazed plate heat exchanger, R-407C',
    description: 'Air-cooled chillers with brazed plate heat exchanger for light commercial cooling applications. Compact design with R-407C refrigerant.',
    features: ['Brazed plate heat exchanger', 'Scroll compressors', 'R-407C refrigerant', 'Compact footprint', '415V / 3Ph / 50Hz'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
    subtitle: 'Brazed Plate Heat Exchanger',
    imageUrl: '/images/acc-bp.png',
  },
  // Chiller Group 5: ACC (Shell & Tube) – Air Cooled, Shell & Tube HX, 20–100 TR, R-407C
  {
    id: 'acc-st',
    groupId: 'chiller',
    name: 'ACC-ST',
    fullName: 'ACC Air-Cooled Chiller with Shell & Tube Heat Exchanger',
    modelPrefix: 'ACC',
    minTons: 20,
    maxTons: 100,
    tonRangeLabel: '20 – 100 Tons',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'Shell & tube heat exchanger, R-407C',
    description: 'Air-cooled chillers with shell & tube heat exchanger for medium commercial and industrial cooling applications. R-407C refrigerant.',
    features: ['Shell & tube heat exchanger', 'Scroll compressors', 'R-407C refrigerant', 'Heavy-duty construction', '415V / 3Ph / 50Hz'],
    isChiller: true,
    isCCU: false,
    hasDualRefrigerant: false,
    subtitle: 'Shell & Tube Heat Exchanger',
    imageUrl: '/images/acc-st.png',
  },
  // CCU group
  {
    id: 'ccu-std',
    groupId: 'ccu',
    name: 'CCU',
    fullName: 'Standard Condensing Unit Series',
    modelPrefix: 'CCU',
    minTons: 32,
    maxTons: 125,
    tonRangeLabel: '32 – 125 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Medium-temperature remote condensing units designed for commercial refrigeration display cases and walk-in coolers.',
    features: [],
    isChiller: false,
    isCCU: true,
    hasDualRefrigerant: false,
    imageUrl: '/images/ccu.png',
  },
  // CRAC – PHE Precision Cooling Unit
  {
    id: 'phe',
    groupId: 'crac',
    name: 'PHE',
    fullName: 'PHE Precision Cooling Unit',
    modelPrefix: 'PHE',
    minTons: 3.5,
    maxTons: 15,
    tonRangeLabel: '3.5 – 15 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Precision cooling, downflow/upflow airflow',
    description: 'PHE precision cooling units for data centers, server rooms, and telecom facilities. Tight temperature and humidity control with R-410A refrigerant. 3.5 to 15 TR capacity range.',
    features: ['Scroll compressors', 'R-410A refrigerant', 'Precision temperature & humidity control', 'Downflow / upflow airflow options', 'EC fan motor option', '415V / 3Ph / 50Hz'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  // Precision cooling
  {
    id: 'prec-dc',
    groupId: 'precision',
    name: 'PDU',
    fullName: 'Precision Data Center Cooling Unit',
    modelPrefix: 'PDU',
    minTons: 5,
    maxTons: 30,
    tonRangeLabel: '5 – 30 Tons',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Precision cooling units for data centers, server rooms, and telecom equipment. Tight temperature and humidity control.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'prec-tele',
    groupId: 'precision',
    name: 'PTU',
    fullName: 'Precision Telecom Cooling Unit',
    modelPrefix: 'PTU',
    minTons: 1,
    maxTons: 10,
    tonRangeLabel: '1 – 10 Tons',
    refrigerants: ['R-410A', 'R-32'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Weatherproof precision cooling units for outdoor telecom shelters, base stations, and remote equipment cabinets.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: true,
  },
  // Fan coil
  {
    id: 'fcu',
    groupId: 'fan-coil',
    name: 'FCU',
    fullName: 'Fan Coil Unit Series',
    modelPrefix: 'FCU',
    minTons: 0.5,
    maxTons: 5,
    tonRangeLabel: '0.5 – 5 Tons',
    cfmRangeLabel: '800 – 2,000 CFM',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'Chilled water fan coil units in concealed horizontal, vertical console, and ceiling cassette configurations.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    imageUrl: '/images/fch.png',
  },
  // FCL Fan Coil Units
  {
    id: 'fcl',
    groupId: 'fan-coil',
    name: 'FCL',
    fullName: 'FCL Chilled Water Fan Coil Unit Series',
    modelPrefix: 'FCL',
    minTons: 0.5,
    maxTons: 30,
    tonRangeLabel: '0.5 – 30 Tons',
    cfmRangeLabel: '200 – 12,000 CFM',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'FCL chilled water fan coil units for a wide range of commercial applications.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    imageUrl: '/images/fcl.png',
  },
  // PNGF / PNGC / CIPK / SPU - Rooftop Packaged
  // NGCC / CHCC / NGCF / CHCF - Split (concealed ducted)
  {
    id: 'pngf',
    groupId: 'pac',
    name: 'PNGF',
    fullName: 'PNGF Rooftop Packaged Series',
    modelPrefix: 'PNGF',
    minTons: 4,
    maxTons: 29,
    tonRangeLabel: '4 – 29 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'PNGF rooftop packaged units with R-410A refrigerant for commercial and industrial cooling. Scroll compressors, 415V/3Ph/50Hz.',
    features: ['Scroll compressors', 'R-410A refrigerant', '415V/3Ph/50Hz', 'Weatherproof rooftop construction'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    speedType: 'fixed',
    imageUrl: '/images/rooftop-pac-2fan.png',
  },
  {
    id: 'pngc',
    groupId: 'pac',
    name: 'PNGC',
    fullName: 'PNGC Rooftop Package Series',
    modelPrefix: 'PNGC',
    minTons: 4,
    maxTons: 33.5,
    tonRangeLabel: '4 – 33.5 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'R-407C, high-ambient Gulf operation',
    description: 'Rooftop packaged units (PNGC-048 to PNGC-400) engineered for high-ambient Gulf climate. Scroll compressors, R-407C refrigerant, 415V/3Ph/50Hz. 16 models from 4 to 33.5 TR.',
    features: ['Scroll compressors', 'R-407C refrigerant', '415V/3Ph/50Hz', 'Weatherproof rooftop construction', 'EER up to 12.8 at 95°F ambient'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    speedType: 'fixed',
    imageUrl: '/images/rooftop-pac-2fan.png',
  },
  {
    id: 'ngcc',
    groupId: 'split',
    name: 'NGCC / NGEC',
    fullName: 'New Generation Compact Ducted Split Series (R-407C)',
    modelPrefix: 'NGEC',
    minTons: 6.3,
    maxTons: 28,
    tonRangeLabel: '6.3 – 28 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'Concealed ducted split, hermetic compressor tropical',
    description: 'New Generation Compact concealed ducted split units (NGCC outdoor / NGEC indoor) designed for tropical climates. Hermetic scroll compressors with R-407C refrigerant, separate outdoor and indoor units. 6.3 to 28 TR.',
    features: ['Hermetic scroll compressors', 'R-407C refrigerant', 'Separate outdoor/indoor units', 'Concealed ducted indoor unit', 'Tropical design'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'ngcf',
    groupId: 'split',
    name: 'NGCF / NGEF',
    fullName: 'New Generation Compact Ducted Split Series (R-410A)',
    modelPrefix: 'NGEF',
    minTons: 6.3,
    maxTons: 28,
    tonRangeLabel: '6.3 – 28 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Concealed ducted split, hermetic compressor tropical',
    description: 'New Generation Compact concealed ducted split units (NGCF outdoor / NGEF indoor) designed for tropical climates. Hermetic scroll compressors with R-410A refrigerant, separate outdoor and indoor units. 6.3 to 28 TR.',
    features: ['Hermetic scroll compressors', 'R-410A refrigerant', 'Separate outdoor/indoor units', 'Concealed ducted indoor unit', 'Tropical design'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'chcc',
    groupId: 'split',
    name: 'CHCC / CHEC',
    fullName: 'Concealed Ducted Split Series (R-407C)',
    modelPrefix: 'CHCC',
    minTons: 2,
    maxTons: 5.6,
    tonRangeLabel: '2 – 5.6 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: 'Concealed ducted, EER up to 14.2',
    description: 'Compact concealed ducted split units (CHCC outdoor / CHEC indoor) with R-407C refrigerant for residential and light commercial applications. High EER ratings up to 14.2. 2 to 5.6 TR.',
    features: ['Scroll compressors', 'R-407C refrigerant', 'Concealed ducted indoor unit', 'EER up to 14.2 at 95°F', 'Compact outdoor unit'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'chcf',
    groupId: 'split',
    name: 'CHCF / CHEF',
    fullName: 'Concealed Ducted Split Series (R-410A)',
    modelPrefix: 'CHCF',
    minTons: 2,
    maxTons: 5.6,
    tonRangeLabel: '2 – 5.6 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: 'Concealed ducted, EER up to 14.2',
    description: 'Compact concealed ducted split units (CHCF outdoor / CHEF indoor) with R-410A refrigerant for residential and light commercial applications. High EER ratings up to 14.2. 2 to 5.6 TR.',
    features: ['Scroll compressors', 'R-410A refrigerant', 'Concealed ducted indoor unit', 'EER up to 14.2 at 95°F', 'Compact outdoor unit'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
  },
  {
    id: 'cipk',
    groupId: 'pac',
    name: 'CIPK',
    fullName: 'CIPK Series',
    modelPrefix: 'CIPK',
    minTons: 4,
    maxTons: 10,
    tonRangeLabel: '4 – 10 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'CIPK series compact packaged units for precision cooling applications.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    speedType: 'variable',
    imageUrl: '/images/rooftop-pac-1fan.png',
  },
  {
    id: 'rpuf',
    groupId: 'pac',
    name: 'RPUF',
    fullName: 'RPUF Rooftop Packaged Series',
    modelPrefix: 'RPUF',
    minTons: 4,
    maxTons: 10,
    tonRangeLabel: '4 – 10 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'RPUF rooftop packaged units with R-410A refrigerant for commercial cooling applications.',
    features: ['Scroll compressors', 'R-410A refrigerant', '415V/3Ph/50Hz', 'Weatherproof rooftop construction'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    speedType: 'fixed',
    imageUrl: '/images/rooftop-pac-1fan.png',
  },
  {
    id: 'rpuc',
    groupId: 'pac',
    name: 'RPUC',
    fullName: 'RPUC Rooftop Packaged Series',
    modelPrefix: 'RPUC',
    minTons: 4,
    maxTons: 10,
    tonRangeLabel: '4 – 10 TR',
    refrigerants: ['R-407C'],
    primaryRefrigerant: 'R-407C',
    keyDifferentiator: '',
    description: 'RPUC rooftop packaged units with R-407C refrigerant for commercial cooling applications.',
    features: ['Scroll compressors', 'R-407C refrigerant', '415V/3Ph/50Hz', 'Weatherproof rooftop construction'],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    speedType: 'fixed',
    imageUrl: '/images/rooftop-pac-1fan.png',
  },
  {
    id: 'spu',
    groupId: 'pac',
    name: 'SPU',
    fullName: 'SPU Series',
    modelPrefix: 'SPU',
    minTons: 35,
    maxTons: 100,
    tonRangeLabel: '35 – 100 TR',
    refrigerants: ['R-410A'],
    primaryRefrigerant: 'R-410A',
    keyDifferentiator: '',
    description: 'SPU series split packaged units for large-capacity commercial cooling applications.',
    features: [],
    isChiller: false,
    isCCU: false,
    hasDualRefrigerant: false,
    speedType: 'fixed',
    imageUrl: '/images/rooftop-pac-4fan.png',
  },
];
