import type { ProductGroup } from '@/types/product';

export const PRODUCT_GROUPS: ProductGroup[] = [
  {
    id: 'pac',
    name: 'Rooftop Packaged',
    description: 'All in one Rooftop Packaged Unit',
    shortDescription: 'All in one Rooftop Packaged Unit',
    category: 'package',
    imageUrl: '/images/pac.png',
    gradientFrom: '#3B82F6',
    gradientTo: '#2563EB',
    seriesCount: 6,
    tonRange: '4 – 100 Tons',
  },
  {
    id: 'split',
    name: 'Split',
    description: 'Indoor and outdoor split systems with separate condensing unit and air handler. Includes concealed ducted and remote condenser configurations for residential and commercial applications.',
    shortDescription: 'Indoor & outdoor split systems',
    category: 'split',
    imageUrl: '/images/split.png',
    gradientFrom: '#7C3AED',
    gradientTo: '#5B21B6',
    seriesCount: 4,
    tonRange: '1.5 – 28 Tons',
  },
  {
    id: 'chiller',
    name: 'Chillers',
    description: 'Air-cooled chillers ranging from 3 to 500 tons. Includes ACSC screw chillers, THAC and ACC brazed plate models, and DHAC and ACC shell & tube models.',
    shortDescription: 'Air Cooled Chillers',
    category: 'chiller',
    imageUrl: '/images/chiller.png',
    gradientFrom: '#14B8A6',
    gradientTo: '#0D9488',
    seriesCount: 5,
    tonRange: '3 – 500 Tons',
  },
  {
    id: 'fan-coil',
    name: 'Fan Coil',
    description: 'DX and chilled water fan coil units for commercial and residential applications. Includes ducted, concealed horizontal, vertical console, and ceiling cassette configurations.',
    shortDescription: 'DX & Chilled Water fan coil units',
    category: 'fan-coil',
    imageUrl: '/images/fcl.png',
    gradientFrom: '#64748B',
    gradientTo: '#475569',
    seriesCount: 3,
    tonRange: '0.5 – 30 Tons',
  },
  {
    id: 'ccu',
    name: 'Condensing Unit',
    description: 'Commercial condensing units for refrigeration and cold storage applications. Designed to pair with custom evaporator coils.',
    shortDescription: 'Commercial condensing units',
    category: 'ccu',
    imageUrl: '/images/ccu.png',
    gradientFrom: '#A855F7',
    gradientTo: '#9333EA',
    seriesCount: 1,
    tonRange: '32 – 125 Tons',
  },
  {
    id: 'crac',
    name: 'CRAC Unit',
    description: 'Computer room air conditioning units for precise temperature and humidity control in data centers and server rooms.',
    shortDescription: 'Data center precision air conditioning',
    category: 'crac',
    imageUrl: '/images/crac.png',
    gradientFrom: '#22C55E',
    gradientTo: '#16A34A',
    seriesCount: 1,
    tonRange: '3.5 – 15 Tons',
  },
  {
    id: 'vrf',
    name: 'VRF',
    description: 'Variable refrigerant flow systems for precise multi-zone temperature control in commercial and residential buildings.',
    shortDescription: 'Multi-zone variable refrigerant flow',
    category: 'vrf',
    imageUrl: '/images/vrf.png',
    gradientFrom: '#1C47DA',
    gradientTo: '#0F36B8',
    seriesCount: 2,
    tonRange: '0.75 – 10 Tons',
  },
];
