import type { ProductGroup } from '@/types/product';

export const PRODUCT_GROUPS: ProductGroup[] = [
  {
    id: 'pac',
    name: 'Rooftop Packaged',
    description: 'Self-contained rooftop and floor-mounted packaged units with integrated condenser. Ideal for commercial and light industrial applications.',
    shortDescription: 'Self-contained rooftop & floor units',
    category: 'package',
    imageUrl: '/images/pac.png',
    gradientFrom: '#0057B8',
    gradientTo: '#003d82',
    seriesCount: 4,
    tonRange: '4 – 100 Tons',
  },
  {
    id: 'split',
    name: 'Split',
    description: 'Split systems with separate outdoor condensing unit and indoor air handler. Includes concealed ducted and remote condenser configurations for residential and commercial applications.',
    shortDescription: 'Concealed ducted & remote condenser split units',
    category: 'split',
    imageUrl: '/images/split.png',
    gradientFrom: '#7C3AED',
    gradientTo: '#5B21B6',
    seriesCount: 6,
    tonRange: '1.5 – 28 Tons',
  },
  {
    id: 'chiller-acsc',
    name: 'ACSC Series',
    description: 'Air-cooled screw chillers with shell & tube evaporator. Hanbell screw compressors engineered for high-ambient Gulf climate operation. R-134a refrigerant.',
    shortDescription: 'Air Cooled Screw Chiller',
    category: 'chiller',
    imageUrl: '/images/chiller.png',
    gradientFrom: '#059669',
    gradientTo: '#047857',
    seriesCount: 1,
    tonRange: '80 – 500 Tons',
  },
  {
    id: 'chiller-thac',
    name: 'THAC Series',
    description: 'Air-cooled chillers with brazed plate heat exchanger. Compact design ideal for small to medium commercial applications. R-410A refrigerant.',
    shortDescription: 'Air Cooled Chiller – Brazed Plate HX',
    category: 'chiller',
    imageUrl: '/images/chiller.png',
    gradientFrom: '#10B981',
    gradientTo: '#059669',
    seriesCount: 1,
    tonRange: '3 – 50 Tons',
  },
  {
    id: 'chiller-dhac',
    name: 'DHAC Series',
    description: 'Air-cooled chillers with shell & tube heat exchanger for medium-capacity applications. Robust design for demanding environments. R-410A refrigerant.',
    shortDescription: 'Air Cooled Chiller – Shell & Tube HX',
    category: 'chiller',
    imageUrl: '/images/chiller.png',
    gradientFrom: '#047857',
    gradientTo: '#065F46',
    seriesCount: 1,
    tonRange: '20 – 100 Tons',
  },
  {
    id: 'chiller-acc-bp',
    name: 'ACC Series (Brazed Plate)',
    description: 'Air-cooled chillers with brazed plate heat exchanger. Compact and efficient for light commercial cooling. R-407C refrigerant.',
    shortDescription: 'Air Cooled Chiller – Brazed Plate HX',
    category: 'chiller',
    imageUrl: '/images/chiller.png',
    gradientFrom: '#34D399',
    gradientTo: '#10B981',
    seriesCount: 1,
    tonRange: '3 – 17 Tons',
  },
  {
    id: 'chiller-acc-st',
    name: 'ACC Series (Shell & Tube)',
    description: 'Air-cooled chillers with shell & tube heat exchanger. Built for medium commercial and industrial cooling. R-407C refrigerant.',
    shortDescription: 'Air Cooled Chiller – Shell & Tube HX',
    category: 'chiller',
    imageUrl: '/images/chiller.png',
    gradientFrom: '#065F46',
    gradientTo: '#064E3B',
    seriesCount: 1,
    tonRange: '20 – 100 Tons',
  },
  {
    id: 'fan-coil',
    name: 'Fan Coil',
    description: 'Two-pipe and four-pipe fan coil units for chilled water distribution systems in hotels, offices, and healthcare facilities.',
    shortDescription: 'Chilled water fan coil units',
    category: 'fan-coil',
    imageUrl: '/images/fan-coil.png',
    gradientFrom: '#00A3E0',
    gradientTo: '#0284C7',
    seriesCount: 1,
    tonRange: '0.5 – 5 Tons',
  },
  {
    id: 'ccu',
    name: 'Condensing Unit',
    description: 'Remote condensing units for refrigeration and cold storage applications. Designed to pair with custom evaporator coils.',
    shortDescription: 'Remote condensing for cold storage',
    category: 'ccu',
    imageUrl: '/images/ccu.png',
    gradientFrom: '#DC2626',
    gradientTo: '#B91C1C',
    seriesCount: 2,
    tonRange: '1 – 25 Tons',
  },
  {
    id: 'crac',
    name: 'CRAC Unit',
    description: 'Computer room air conditioning units for precise temperature and humidity control in data centers and server rooms.',
    shortDescription: 'Data center precision air conditioning',
    category: 'crac',
    imageUrl: '/images/crac.png',
    gradientFrom: '#6366F1',
    gradientTo: '#4F46E5',
    seriesCount: 3,
    tonRange: '1 – 30 Tons',
  },
  {
    id: 'vrf',
    name: 'VRF',
    description: 'Variable refrigerant flow systems for precise multi-zone temperature control in commercial and residential buildings.',
    shortDescription: 'Multi-zone variable refrigerant flow',
    category: 'vrf',
    imageUrl: '/images/vrf.png',
    gradientFrom: '#F59E0B',
    gradientTo: '#D97706',
    seriesCount: 2,
    tonRange: '0.75 – 10 Tons',
  },
];
