import type { Project } from '@/types/project';

export const MOCK_PROJECTS: Project[] = [
  {
    id: 'proj-001',
    name: 'Al Hamra Village Phase 3',
    clientName: 'Al Hamra Real Estate',
    salesEngineer: 'Ahmed Al-Rashidi',
    status: 'active',
    createdAt: '2026-01-15T08:00:00Z',
    updatedAt: '2026-02-28T14:32:00Z',
    country: 'Kuwait',
    submittedFor: 'Mechanical Contractor',
    units: [
      {
        id: 'unit-001a',
        projectId: 'proj-001',
        tag: 'AHU-01',
        reference: 'Clubhouse Main AHU',
        seriesId: 'pac-r',
        seriesName: 'PAC-R',
        model: {
          id: 'pac-r-CPACR0300',
          seriesId: 'pac-r',
          modelNumber: 'CPACR0300',
          totalCapacityBtuh: 360000,
          sensibleCapacityBtuh: 259200,
          powerKW: 37.5,
          eer: 9.8,
          airflowCFM: 12000,
          leavingDBF: 58,
          leavingWBF: 53,
          compressorCount: 4,
          matchPercent: 97,
          nominalTons: 30,
          weightLbs: 1500,
          lengthIn: 126,
          widthIn: 65,
          heightIn: 60,
        },
        quantity: 2,
        revisions: [
          { id: 'rev-001a-001', unitId: 'unit-001a', revisionNumber: '001', createdAt: '2026-01-15T08:00:00Z', createdBy: 'Ahmed Al-Rashidi', changeSummary: 'Initial selection — 30-ton PAC-R', status: 'superseded' },
          { id: 'rev-001a-002', unitId: 'unit-001a', revisionNumber: '002', createdAt: '2026-02-10T10:15:00Z', createdBy: 'Ahmed Al-Rashidi', changeSummary: 'Added BACnet option + stainless drain pan', status: 'issued' },
        ],
        currentRevision: '002',
      },
    ],
  },
  {
    id: 'proj-002',
    name: 'Gulf Bank HQ Data Center',
    clientName: 'Gulf Bank K.S.C.P.',
    salesEngineer: 'Sara Al-Mutairi',
    status: 'submitted',
    createdAt: '2026-01-22T10:00:00Z',
    updatedAt: '2026-02-20T16:00:00Z',
    country: 'Kuwait',
    submittedFor: 'Facilities Management',
    units: [
      {
        id: 'unit-002a',
        projectId: 'proj-002',
        tag: 'PDU-01',
        reference: 'Server Room A Precision Cooling',
        seriesId: 'prec-dc',
        seriesName: 'PDU',
        model: {
          id: 'prec-dc-CPDU0150',
          seriesId: 'prec-dc',
          modelNumber: 'CPDU0150',
          totalCapacityBtuh: 180000,
          sensibleCapacityBtuh: 129600,
          powerKW: 18.5,
          eer: 10.5,
          airflowCFM: 6000,
          leavingDBF: 65,
          leavingWBF: 57,
          compressorCount: 2,
          matchPercent: 100,
          nominalTons: 15,
          weightLbs: 825,
          lengthIn: 78,
          widthIn: 42,
          heightIn: 48,
        },
        quantity: 3,
        revisions: [
          { id: 'rev-002a-001', unitId: 'unit-002a', revisionNumber: '001', createdAt: '2026-01-22T10:00:00Z', createdBy: 'Sara Al-Mutairi', changeSummary: 'Initial selection — 15-ton PDU precision cooling', status: 'issued' },
        ],
        currentRevision: '001',
      },
    ],
  },
  {
    id: 'proj-003',
    name: 'Jahra Hypermarket Refrigeration',
    clientName: 'Tamimi Markets',
    salesEngineer: 'Mohammed Al-Enezi',
    status: 'draft',
    createdAt: '2026-02-05T09:30:00Z',
    updatedAt: '2026-02-25T11:00:00Z',
    country: 'Kuwait',
    submittedFor: 'End User',
    units: [
      {
        id: 'unit-003a',
        projectId: 'proj-003',
        tag: 'CCU-01',
        reference: 'Produce Walk-in Cooler',
        seriesId: 'ccu-std',
        seriesName: 'CCU',
        model: {
          id: 'ccu-std-CCCU0050',
          seriesId: 'ccu-std',
          modelNumber: 'CCCU0050',
          totalCapacityBtuh: 60000,
          sensibleCapacityBtuh: 43200,
          powerKW: 6.8,
          eer: 9.5,
          airflowCFM: 2000,
          leavingDBF: 35,
          leavingWBF: 32,
          compressorCount: 1,
          matchPercent: 95,
          nominalTons: 5,
          weightLbs: 375,
          lengthIn: 46,
          widthIn: 27,
          heightIn: 40,
        },
        quantity: 4,
        revisions: [
          { id: 'rev-003a-001', unitId: 'unit-003a', revisionNumber: '001', createdAt: '2026-02-05T09:30:00Z', createdBy: 'Mohammed Al-Enezi', changeSummary: 'Initial selection — 5-ton CCU for produce cooler', status: 'draft' },
        ],
        currentRevision: '001',
      },
    ],
  },
  {
    id: 'proj-004',
    name: 'Avenues Mall Expansion Wing',
    clientName: 'Mabanee Company',
    salesEngineer: 'Ahmed Al-Rashidi',
    status: 'approved',
    createdAt: '2025-11-10T08:00:00Z',
    updatedAt: '2026-01-30T09:00:00Z',
    country: 'Kuwait',
    submittedFor: 'General Contractor',
    units: [],
  },
  {
    id: 'proj-005',
    name: 'Khobar Pharmaceutical Warehouse',
    clientName: 'Gulf Pharma Distribution',
    salesEngineer: 'Sara Al-Mutairi',
    status: 'active',
    createdAt: '2026-02-14T11:00:00Z',
    updatedAt: '2026-02-27T15:45:00Z',
    country: 'Saudi Arabia',
    submittedFor: 'Mechanical Contractor',
    units: [],
  },
];
